/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanner1309
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogros = new javax.swing.JLabel();
        btnRapida = new javax.swing.JLabel();
        btnUnica = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        InfoBar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JLabel();
        Titlebar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema neon/Plantillas/menuprincipal/btnLogros.png"))); // NOI18N
        getContentPane().add(btnLogros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, -1, -1));

        btnRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema neon/Plantillas/menuprincipal/btnRapida.png"))); // NOI18N
        btnRapida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRapidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRapidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRapidaMouseExited(evt);
            }
        });
        getContentPane().add(btnRapida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        btnUnica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema neon/Plantillas/menuprincipal/BtnUnica.png"))); // NOI18N
        btnUnica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUnicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUnicaMouseExited(evt);
            }
        });
        getContentPane().add(btnUnica, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        lblMensaje.setFont(new java.awt.Font("Nunito Black", 1, 18)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("Bienvenido! Selecciona un modo de juego");
        getContentPane().add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, 580, -1));

        InfoBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema neon/Plantillas/menuprincipal/Informacion.png"))); // NOI18N
        getContentPane().add(InfoBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema neon/Plantillas/menuprincipal/Cerrar.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 635, 90, 90));

        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema neon/Plantillas/menuprincipal/Ajustes.png"))); // NOI18N
        getContentPane().add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 610, -1, -1));

        Titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema neon/Plantillas/menuprincipal/Titlbar.png"))); // NOI18N
        getContentPane().add(Titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema neon/Plantillas/MenuPrincipal.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRapidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRapidaMouseEntered
        // TODO add your handling code here:
        lblMensaje.setText("Palabra aleatoria 6 intentos,juega las veces que quieras");
    }//GEN-LAST:event_btnRapidaMouseEntered

    private void btnRapidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRapidaMouseExited
        // TODO add your handling code here:
         lblMensaje.setText("Bienvenido! Selecciona un modo de juego");
    }//GEN-LAST:event_btnRapidaMouseExited

    private void btnUnicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnicaMouseEntered
        // TODO add your handling code here:
        lblMensaje.setText("Personaliza la partida a tu gusto");
    }//GEN-LAST:event_btnUnicaMouseEntered

    private void btnUnicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnicaMouseExited
        // TODO add your handling code here:
        lblMensaje.setText("Bienvenido! Selecciona un modo de juego");
    }//GEN-LAST:event_btnUnicaMouseExited

    private void btnRapidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRapidaMouseClicked
        // TODO add your handling code here:
        PartidaRapida partidarapida=new PartidaRapida();
        partidarapida.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRapidaMouseClicked

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        // TODO add your handling code here:
        lblMensaje.setText("Cerrar Juego");
        
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        // TODO add your handling code here:
         lblMensaje.setText("Bienvenido! Selecciona un modo de juego");
    }//GEN-LAST:event_btnCerrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel InfoBar;
    private javax.swing.JLabel Titlebar;
    private javax.swing.JLabel btnAjustes;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnLogros;
    private javax.swing.JLabel btnRapida;
    private javax.swing.JLabel btnUnica;
    private javax.swing.JLabel lblMensaje;
    // End of variables declaration//GEN-END:variables
}
